services:
  catalogdb:
      container_name: catalogdb_container
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=CatalogDb
      restart: always
      ports:
        - "5432:5432"
      volumes:
        - postgres_catalog:/var/lib/postgresql/18/docker
# docker run --help' docker run --name catalogdb_container -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=CatalogDb -p 5432:5432 -d postgres:18
# To connect to the container
# docker exec -it 89f52d607859 bash

# To connect 
# psql -U postgres

# To list
# \l

# To connect to the CatalogDb database
# \c CatalogDb

# To list tables
# \d

# To view data
# SELECT * FROM mt_doc_product;