services:
  catalogdb:
      container_name: catalogdb_container
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=CatalogDb
      restart: always
      ports:
        - "5432:5432"
      volumes:
        - postgres_catalog:/var/lib/postgresql/18/docker
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=catalogdb;Port=5432;Database=CatalogDb;User Id=postgres;Password=postgres;Include Error Detail=true
    depends_on:
      - catalogdb
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro 

# docker run --help' 
# docker run --name catalogdb_container -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=CatalogDb -p 5432:5432 -d postgres:18
# To connect to the container
# docker exec -it 89f52d607859 bash

# To connect 
# psql -U postgres
# psql -h 127.0.0.1 -p 5432 -U postgres -W -c '\l'

# To list
# \l

# To connect to the CatalogDb database
# \c CatalogDb

# To list tables
# \d

# To view data
# SELECT * FROM mt_doc_product;

# docker-compose -f docker-compose.yml -f docker-compose.override.yml up -d